# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='age',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='amputation_cause',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='amputation_level',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r1',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r10',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r11',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r12',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r13',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r14',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r15',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r16',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r2',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r3',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r4',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r5',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r6',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r7',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r8',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='r9',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='race',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='response',
            name='sex',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
